// <auto-generated />
using GlimpsesOfGlory.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlimpsesOfGlory.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801013633_AddAdminProductAndShippingManagement")]
    partial class AddAdminProductAndShippingManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlimpsesOfGlory.Core.Products.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Placeholder description for sample product one. Replace with real product copy.",
                            IsActive = true,
                            Name = "Sample Product One",
                            Price = 19.99m,
                            Slug = "sample-product-one",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Placeholder description for sample product two. Replace with real product copy.",
                            IsActive = true,
                            Name = "Sample Product Two",
                            Price = 29.99m,
                            Slug = "sample-product-two",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Placeholder description for sample product three. Replace with real product copy.",
                            IsActive = true,
                            Name = "Sample Product Three",
                            Price = 39.99m,
                            Slug = "sample-product-three",
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("GlimpsesOfGlory.Core.Products.Entities.ProductPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            FileName = "sample-product-one-1.svg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            FileName = "sample-product-one-2.svg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            FileName = "sample-product-two-1.svg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 2,
                            FileName = "sample-product-two-2.svg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            FileName = "sample-product-three-1.svg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            FileName = "sample-product-three-2.svg",
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("GlimpsesOfGlory.Core.Shipping.Entities.ShippingTierSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShippingTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5.00m,
                            MinQuantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 9.00m,
                            MinQuantity = 5
                        });
                });

            modelBuilder.Entity("GlimpsesOfGlory.Core.Products.Entities.ProductPhoto", b =>
                {
                    b.HasOne("GlimpsesOfGlory.Core.Products.Entities.Product", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlimpsesOfGlory.Core.Products.Entities.Product", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
